Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "rhum")
Ingredient.create(name: "gin")
Ingredient.create(name: "sugar cane")
Ingredient.create(name: "orange juice")
