Ingredient.create(name: "campari")
Ingredient.create(name: "coco milk")
Ingredient.create(name: "cranberry juice")
Ingredient.create(name: "ice")
Ingredient.create(name: "fizzy water")
Ingredient.create(name: "gin")
Ingredient.create(name: "lime")
Ingredient.create(name: "martini")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "olives")
Ingredient.create(name: "orange juice")
Ingredient.create(name: "pineaple juice")
Ingredient.create(name: "red martini")
Ingredient.create(name: "rhum")
Ingredient.create(name: "strawberry mash")
Ingredient.create(name: "sugar cane")
Ingredient.create(name: "triple sec")
Ingredient.create(name: "vodka")



# Cocktail.create(name: "Tequila sunrise")
# Cocktail.create(name: "Mojito")
# Cocktail.create(name: "Punch")

# Dose.create(description: "2cl de rhum", cocktail_id: 2, ingredient_id: 4)
# Dose.create(description: "5 ou 6 feuilles de menthe", cocktail_id: 2, ingredient_id: 3)
# Dose.create(description: "un peu de citron vert", cocktail_id: 2, ingredient_id: 1)
# Dose.create(description: "et du sucre de canne liquide", cocktail_id: 2, ingredient_id: 6)
